### ISSUE TITLE
OLTU library should respect JIRA/Confluence proxy settings

### ISSUE THREAD

**Issue by pawelniewie** [pawelniewie/social-authentication-for-atlassian#17]
https://confluence.atlassian.com/jirakb/how-to-configure-an-outbound-http-and-https-proxy-for-jira-applications-247857187.html

**Comment by WetHippie** [comment]
I've now run into this problem. Something changed between the 3.1.7 version and 3.2.0. The older version worked fine and used the outbound proxies. The latest version does not work as expected and tries to directly access the outside world.

`2018-04-27 03:00:06,467 http-nio-8080-exec-22 ERROR anonymous 177x673x1 1wt79bl 172.16.50.4,0:0:0:0:0:0:0:1 /openid/oauth2-callback/google [c.p.j.o.authentication.servlet.OAuthCallbackServlet] OpenID verification failed
org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.net.ConnectException: Connection timed out (Connection timed out)
	at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:116)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
	at com.pawelniewiadomski.jira.openid.authentication.providers.GoogleProviderType.getUsernameAndEmail(GoogleProviderType.java:106)
	at com.pawelniewiadomski.jira.openid.authentication.servlet.OAuthCallbackServlet.doGet(OAuthCallbackServlet.java:76)
....
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at org.apache.oltu.oauth2.client.URLConnectionClient.setRequestBody(URLConnectionClient.java:132)
	at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:99)

`

Even though it is using the JDK libraries, it seems that things are now broken. Please fix ASAP as it has stuffed all our users that have had their session time out.

**Comment by WetHippie** [comment]
Please note that I have the proxy settings set (as well as nonProxyHosts) and the rest of JIRA happily talks to the outside world as needed. That means there's something in your code that explicitly disables them, which is not nice. Remove that and let the system use whatever the command line gives it and things would be great.

**Comment by pawelniewie** [comment]
Thanks for reporting this and sorry for the trouble. I think OLTU update broken it. Going to fix it soon.

**Comment by pawelniewie** [comment]
I just released a fix that brings back correct proxy support.

**Comment by pawelniewie** [comment]
Awesome! 🇦🇺

**Comment by WetHippie** [comment]
Confirmed working for both JIRA and Confluence. Thanks again for the rapid response. I have happy users again!
