### ISSUE TITLE
Investigate and fix ClassCastException

### ISSUE THREAD

**Issue by pawelniewie** [pawelniewie/social-authentication-for-atlassian#44]
```
2017-12-14 11:15:45,364 http-nio-127.0.0.101-8080-exec-8 ERROR anonymous 675x1356x1 3ilcc9 216.82.58.124,127.0.0.1 /o
penid/oauth2-callback/0b7ff79d-bf6a-4b1f-84c0-6e9866439151 [c.p.j.o.authentication.servlet.OAuthCallbackServlet] Open
ID verification failed
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
        at org.apache.oltu.oauth2.jwt.io.JWTClaimsSetParser.handleProperty(JWTClaimsSetParser.java:33)
        at org.apache.oltu.commons.json.CustomizableEntityReader.read(CustomizableEntityReader.java:92)
        at org.apache.oltu.oauth2.jwt.io.JWTReader.build(JWTReader.java:32)
        at org.apache.oltu.oauth2.jwt.io.JWTReader.build(JWTReader.java:25)
        at org.apache.oltu.commons.encodedtoken.TokenReader.read(TokenReader.java:79)
        at com.pawelniewiadomski.jira.openid.authentication.openid.OpenIdConnectResponse.init(OpenIdConnectResponse.j
ava:36)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponse
Factory.java:60)
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:111)
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
        at com.pawelniewiadomski.jira.openid.authentication.providers.DiscoverablyOauth2ProviderType.getUsernameAndEm
ail(DiscoverablyOauth2ProviderType.java:204)
```

**Comment by pawelniewie** [comment]
Updated oltu with a version that should not throw this error.
