### ISSUE TITLE
Google authentication randomly fails

### ISSUE THREAD

**Issue by pawelniewie** [pawelniewie/social-authentication-for-atlassian#66]
During the trial of JIRA OIDC Connector, I found that it now has a bug that would prevent some users from using the extension. Not quite clear what triggers that -- it all seems random (probably Google is running some kind of experiment?)

Specifically, the problem is that Google returns URL safe Base64 encoded string instead of normal base64 strings. The traceback looks like:

java.lang.IllegalArgumentException: XXXX.XXXX.XXXX not a valid Token, it does not match with the pattern: ([a-zA-Z0-9/+=]+)\.([a-zA-Z0-9/+=]+)\.(.+)
        at org.apache.oltu.commons.encodedtoken.TokenReader.read(TokenReader.java:62)
        at com.pawelniewiadomski.jira.openid.authentication.openid.OpenIdConnectResponse.lambda$getIdToken$0(OpenIdConnectResponse.java:39)
        at java.util.Optional.map(Optional.java:215)

The bug was already fixed from upstream (https://github.com/apache/oltu/commit/ec5d53b8e9f9d798079ab6014c8d5d24e86dc16d). Please update your dependencies, and hopefully this bug would be fixed.

**Comment by pawelniewie** [comment]
Releasing 3.3.2 with a fix.
