### ISSUE TITLE
GitHub authentication fails when user's email address is private

### ISSUE THREAD

**Issue by jamesedwardpierce** [pawelniewie/social-authentication-for-atlassian#8]
A new behavior with GitHub has occurred that GitHub authentication to fail in Jira when the user's email address in his GitHub profile is marked private.  Simply making his email address public resolves the problem.

The error that was logged in Jira is ...
2017-02-13 22:11:12,125 http-nio-8080-exec-19 ERROR anonymous 1331x7051x1 13gzn5v 10.44.96.9 /openid/oauth2-callback/github [c.p.j.o.authentication.servlet.OAuthCallbackServlet] OpenID verification failed
org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "visibility" (Class com.pawelniewiadomski.jira.openid.authentication.providers.EmailResponse), not marked as ignorable
 at [Source: java.io.StringReader@11d57870; line: 1, column: 80] (through reference chain: com.pawelniewiadomski.jira.openid.authentication.providers.EmailResponse["visibility"])
	at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
	at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:649)
	at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:635)
	at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1355)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:717)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:194)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1861)
	at com.pawelniewiadomski.jira.openid.authentication.providers.GitHubProviderType.getUsernameAndEmail(GitHubProviderType.java:107)
	at com.pawelniewiadomski.jira.openid.authentication.servlet.OAuthCallbackServlet.doGet(OAuthCallbackServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.atlassian.plugin.servlet.DelegatingPluginServlet.service(DelegatingPluginServlet.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.atlassian.plugin.servlet.ServletModuleContainerServlet.service(ServletModuleContainerServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	... 242 filtered
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pawelniewie** [comment]
Thanks, I will fix that soon, seems like a new field was added to the response and it can't handle it.

**Comment by pawelniewie** [comment]
Please try this version https://dl.dropboxusercontent.com/u/2052049/jira-openid-authentication-plugin-3.0.6-SNAPSHOT.jar

**Comment by pawelniewie** [comment]
Fixed in 3.0.6
